apiVersion: v1
kind: Service
metadata:
  name: fl-helm-nginx
  labels:
    app.kubernetes.io/name: fl-nginx
    app.kubernetes.io/instance: fl-helm-nginx
    app.kubernetes.io/part-of: flashlearn-gitops-demo
spec:
  selector:
    app.kubernetes.io/instance: fl-helm-nginx
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http