apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fl-dev
resources:
  - ../../../apps/nginx
patches:
  - target:
      kind: Ingress
      name: fl-nginx
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev-nginx.fl.local